### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by hooooooot** [Arsennnic/ustc-epc-bot#5]
当已经约满4个学时而再运行软件的时候，会先取消掉最靠后的一节课，随后才进行课表优化。它取消了我第9周的课，然后给我预约了一个第10周的。。。

**Comment by Arsennnic** [comment]
请问这是偶然情况, 还是经常发生的呢?

**Comment by hooooooot** [comment]
试了两次，都是这样。不敢再试了。。

**Comment by Arsennnic** [comment]
明白了, 我会排查一下BUG.
方便的话能不能提供一下你的账号密码, 我已经没有选课权限了.
可以通过邮箱 arsennnic@gmail.com 与我联系.

**Comment by Arsennnic** [comment]
经过一段时间的运行, 基本可以确定BUG得到修复. 
晚些时候会重新打包上传v2.1版本.
![](https://user-images.githubusercontent.com/23273199/77877498-84f52b00-7288-11ea-8d8f-5196cbcd334b.png)
